#@ load("@ytt:data", "data")
---
apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  name: #@ data.values.app_name
  labels:
    app: #@ data.values.app_name
spec:
  replicas: 3
  workerOptions:
    connectionRef:
      name: donald-demo
    temporalNamespace: donald-demo
  rollout:
    strategy: Progressive
    steps: 
      - rampPercent: 1
        pauseDuration: 10m
      - rampPercent: 50
        pauseDuration: 15m 
  sunset:
    scaleddownDelay: 30m
    deleteDelay: 60m
  selector:
    matchLabels:
      app: #@ data.values.app_name
  template:
    metadata:
      labels:
        app: #@ data.values.app_name
    spec:
      containers:
        - name: temporal-worker-versioning-demo
          image: #@ data.values.image.url
          imagePullPolicy: Always
          env:
            - name: ENCRYPT_PAYLOADS
              value: "false"
            - name: TEMPORAL_CERT_PATH
              value: /etc/certs/tls.crt
            - name: TEMPORAL_KEY_PATH
              value: /etc/certs/tls.key
          volumeMounts:
            - mountPath: /etc/certs
              name: certs
      volumes:
        - name: certs
          secret:
            defaultMode: 420
            secretName: temporal-auth-tls
