server: 
  address: 0.0.0.0
  port: 6080

management:
  endpoints:
    web: 
      exposure:
        include: prometheus,temporalworkerinfo

spring:
  application:
    name: "worker-versioning"
  temporal:
    namespace: ${TEMPORAL_NAMESPACE:default}
    workersAutoDiscovery:
      packages: 
        - io.temporal.demos.worker_versioning
        - io.temporal.spring.boot.autoconfigure.workerversioning

    connection:
      target: ${TEMPORAL_ADDRESS:127.0.0.1:7233}
      mtls:
        key-file: ${TEMPORAL_KEY_PATH:/Users/donald/stuff/source/certificates/temporal-client.key}
        cert-chain-file: ${TEMPORAL_CERT_PATH:/Users/donald/stuff/source/certificates/temporal-client-leaf.pem}
    # (Note following configuration are not set by default but serve more as reference)
    workers:
      - name: MarketingWorker
        task-queue: MarketingWorkerVersioning
        deployment-properties:
          deployment-version: "${TEMPORAL_DEPLOYMENT_NAME}.${TEMPORAL_WORKER_BUILD_ID}:temporal-worker-versioning.@project.version@"
          use-versioning: true
          default-versioning-behavior: "AUTO_UPGRADE"
        workflow-classes:
          - io.temporal.demos.worker_versioning.workflows.MarketingWorkflowImpl
        activity-beans:
          - marketingActivitiesImpl

      - name: OnboardingWorker
        task-queue: OnboardingWorkerVersioning
        deployment-properties:
          deployment-version: "${TEMPORAL_DEPLOYMENT_NAME}-Onboarding.${TEMPORAL_WORKER_BUILD_ID}"
          use-versioning: true
          default-versioning-behavior: "PINNED"

