name: temporal-worker-versioning-demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUILDER: "paketobuildpacks/builder-jammy-base/"
  IMG_NAME: temporal-worker-versioning-demo
  USERNAME: donaldf


jobs:
  register:
    name: Package, Publish, Register
    runs-on:
    - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Setup QEMU (Multi-arch)
      uses: docker/setup-qemu-action@v2

    - name: Log in to ghcr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - id: setup-tools
      uses: buildpacks/github-actions/setup-tools@v5.9.5
      
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v5.9.5
      
    - id: package
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        # TODO - Get the version from app centrally...
        VERSION="1.0.0"
        
        pack build ghcr.io/${{ github.repository_owner }}/${{ env.IMG_NAME }}:$VERSION --builder ${{ env.BUILDER }} --publish      
        DIGEST="$(crane digest ${{ env.IMG_NAME }}:${VERSION})"
        echo "id=${{ env.IMG_NAME }}"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "address=${PACKAGE}@${DIGEST}" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
        
    - id: register
      uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:5.9.5
      with:
        token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
        id:      ${{ steps.package.outputs.id }}
        version: ${{ steps.package.outputs.version }}
        address: ${{ steps.package.outputs.address }}   
